### ISSUE TITLE
Projet MIDO - Erreur 404 pour la Ref "Voir dessin à la main."

### ISSUE THREAD

**Issue by Cocolollipop** [oliviercailloux/java-course#2]
Contexte: Sur la page de présentation du projet MIDO SVG
    Lien: https://github.com/oliviercailloux/projets/blob/master/mido_svg.adoc

Issue: Erreur 404 pour la Ref "Voir dessin à la main." (bas de page)

Solution: Lien à mettre à jour en:
https://github.com/oliviercailloux/projets/blob/master/MIDO-Svg/MIDO.svg

**Comment by oliviercailloux** [comment]
Merci
