### ISSUE TITLE
[SITN][Devoir JPA] contrainte JUnit5 et arquillian 

### ISSUE THREAD

**Issue by DBarthe** [oliviercailloux/java-course#5]
Bonjour,

Dans la  [consigne du devoir JPA](https://github.com/oliviercailloux/java-course/blob/master/Divers/SITN.adoc#s6-vendredi-22-f%C3%A9vrier), il est demandé d'utiliser JUnit5, mais il est aussi proposé d'utiliser Arquillian pour le test fonctionnel.

Or, Arquillian ne fonctionne pas avec JUnit5, mais avec JUnit4.

Personnellement j'ai utilisé Arquillian avec JUnit4 et j'espère que ca ne posera pas de problème pour l'évaluation.

Merci d'avance,
Barthélémy Delemotte

**Comment by oliviercailloux** [comment]
Ok !
