### ISSUE TITLE
Difficultés projet Plaquette-MIDO

### ISSUE THREAD

**Issue by camillelanglois3** [oliviercailloux/java-course#6]
Bonjour monsieur, 

Nous rencontrons des difficultés dans la compilation du projet plaquette-Mido, plus particulièrement lors de la phase mvn generate-sources où nous avons l'erreur suivante : Failed to execute goal com.sun.xml.ws:jaxws-maven-plugin:2.3.2:wsimport (default) on project plaquette-mido: Mojo failed - check output -> [Help 1]
Et nous sommes bloqués car ne pouvons pas comprendre le projet toutes ces erreurs

**Comment by oliviercailloux** [comment]
“check output” suggère qu’il y a plus d’information disponible. Pouvez-vous copier la commande que vous exécutez et le résultat complet ?

Le plugin `com.sun.xml.ws:jaxws-maven-plugin` permet de générer des classes pour aider à accéder à un service web. Dans notre cas, c’est un service web de Dauphine, accessible à https://rof.testapi.dauphine.fr/ebx-dataservices/tables/pvRefRof/RefRof?WSDL. Mais il n’est accessible qu’après login (nom d’utilisateur et mot de passe).

Vous pouvez vérifier que vous avez accès au service web avec votre navigateur, en utilisant le login que vous avez reçu précédemment (cf. échanges avec Marcellino et l’équipe de Teach spreadsheets). Si ça fonctionne, vous devriez voir un fichier XML (WSDL) contenant un descriptif du service web.

Si ça fonctionne, il faut créer un fichier WSDL_access.txt contenant le `https://username:password@*`, en remplaçant `username` et `password` par votre login, et en n’oubliant pas le `@*` à la fin (qui indique que ce login doit être utilisé pour toutes les adresses).

Tenez-moi au courant.

**Comment by camillelanglois3** [comment]
Oui nous arrivons bien à nous connecter avec notre navigateur aucun soucis merci beaucoup.
J'ai créé le fichier WSDL_access.txt et à présent la commande mvn compile ne génère plus d'erreur, ça a réglé ce problème. 
En revanche sur eclipse tout est encore souligné en rouge et il semble toujours y avoir un problème dans le pom.xml, y a-t-il une manipulation particulière à faire afin de régler le problème ?

Merci beaucoup pour votre aide

**Comment by camillelanglois3** [comment]
Par souligné en rouge j'entend que les classes EbxDataservices, ObjectFactory ou autres ne sont pas connues et dans le pom.xml la partie exécution avec wsimport semble poser problème

**Comment by oliviercailloux** [comment]
Eclipse vous avertit qu’il ne connait pas ce plugin, comme j’écrivais à Marcellino. Vous pouvez demander à Eclipse d’ignorer le problème (sans l’autoriser à écrire dans le POM, cependant). 

Il faut ajouter les classes générées par Maven (dans `target/generated-sources/wsimport`) au build path pour que Eclipse les prenne en compte.

**Comment by camillelanglois3** [comment]
Merci beaucoup, cela a réglé le problème.

**Comment by oliviercailloux** [comment]
Parfait ! N’oubliez pas de fermer cette Issue, qu’on s’y retrouve.
